//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY
    {
        public string CreateBy_id { get; set; }
        public int Category_id { get; set; }
        public string Category_Name { get; set; }
        public string Category_Content { get; set; }
    }
}
